### ISSUE TITLE
Mage registry key "_resource_singleton/aoe_scheduler/job" already exists

### ISSUE THREAD

**Issue by fbrnc** [AOEpeople/Aoe_Scheduler#108]
### Mage registry key "_resource_singleton/aoe_scheduler/job" already exists

```
#0 /var/www/example/production/releases/build_299/htdocs/app/Mage.php(222): Mage::throwException('Mage registry k...')
#1 /var/www/example/production/releases/build_299/htdocs/app/Mage.php(518): Mage::register('_resource_singl...', false)
#2 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/Abstract.php(139): Mage::getResourceSingleton('aoe_scheduler/j...')
#3 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/Abstract.php(208): Mage_Core_Model_Abstract->_getResource()
#4 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/Abstract.php(213): Mage_Core_Model_Abstract->getResourceCollection()
#5 /var/www/example/production/releases/build_299/.modman/aoe_scheduler/app/code/community/Aoe/Scheduler/Model/ScheduleManager.php(143): Mage_Core_Model_Abstract->getCollection()
#6 /var/www/example/production/releases/build_299/.modman/aoe_scheduler/app/code/community/Aoe/Scheduler/Model/Observer.php(43): Aoe_Scheduler_Model_ScheduleManager->generateSchedules()
#7 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/App.php(1338): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#8 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#9 /var/www/example/production/releases/build_299/htdocs/app/Mage.php(447): Mage_Core_Model_App->dispatchEvent('default', Array)
#10 /var/www/example/production/releases/build_299/htdocs/cron.php(73): Mage::dispatchEvent('default')
#11 {main}
```

**Comment by LeeSaferite** [comment]
This is again an error you should never be able to provoke.

The call to `Mage::getResourceSingleton()` actually checks if the registry entry exists before it tries to instantiate it. I would imagine something is seriously wrong with the server you got this message from.

**Comment by fplantinet** [comment]
Afer update, clean redis cache, solve bug for me
