### ISSUE TITLE
Can't get the cron jobs to work anymore

### ISSUE THREAD

**Issue by pmeems** [AOEpeople/Aoe_Scheduler#227]
I use AOE v1.3 and since two weeks I have trouble with the cron jobs in Magento. At that time I was still using AOE v0.9. So I first updated to v1.3 but the issues persisted.
Today our Magento CE v1.9.2.2 was moved to a new server with  CentOS 7.2 and PHP v5.5.31.
I had hoped this would solve our problems but it doesn't.
When I hit the 'Generate Schedule' button I get this error:

There has been an error processing your request
Invalid cron expression: 
Trace:
#0 /home/scrapweb/public_html/app/code/core/Mage/Cron/Model/Schedule.php(162): Mage::exception('Mage_Cron', 'Invalid cron ex...')
#1 /home/scrapweb/public_html/app/code/core/Mage/Cron/Model/Schedule.php(96): Mage_Cron_Model_Schedule->matchCronExpression('/5', 10)
#2 /home/scrapweb/public_html/app/code/community/Aoe/Scheduler/Model/ScheduleManager.php(245): Mage_Cron_Model_Schedule->trySchedule(1453369271)
#3 /home/scrapweb/public_html/app/code/community/Aoe/Scheduler/Model/ScheduleManager.php(147): Aoe_Scheduler_Model_ScheduleManager->generateSchedulesForJob(Object(Aoe_Scheduler_Model_Job))
#4 /home/scrapweb/public_html/app/code/community/Aoe/Scheduler/Controller/AbstractController.php(102): Aoe_Scheduler_Model_ScheduleManager->generateSchedules()
#5 /home/scrapweb/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Aoe_Scheduler_Controller_AbstractController->generateScheduleAction()
#6 /home/scrapweb/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('generateSchedul...')
#7 /home/scrapweb/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /home/scrapweb/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#9 /home/scrapweb/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /home/scrapweb/public_html/index.php(83): Mage::run('', 'store')
#11 {main}

What is going wrong? What do I need to do to enable this great extension again?

Thanks,
Paul

**Comment by riconeitzel** [comment]
you might have a wrong cron expression in any of your cron jobs scheduled in magento …
