### ISSUE TITLE
Can't lock indexer process Issue

### ISSUE THREAD

**Issue by sathishramesh1989** [AOEpeople/Aoe_Scheduler#237]
While Running CRON we are getting the below error in cron_schedule table.

---EXCEPTION---
exception 'Enterprise_Index_Exception' with message 'Can't lock indexer process.' in app/code/core/Enterprise/Index/Model/Observer.php:140
Stack trace:
#0 [internal function]: Enterprise_Index_Model_Observer->refreshIndex(Object(Aoe_Scheduler_Model_Schedule))
#1 app/code/community/Aoe/Scheduler/Model/Schedule.php(196): call_user_func_array(Array, Array)
#2 app/code/community/Aoe/Scheduler/Model/Schedule.php(582): Aoe_Scheduler_Model_Schedule->runNow(false)
#3 app/code/community/Aoe/Scheduler/Model/Observer.php(79): Aoe_Scheduler_Model_Schedule->process()
#4 app/code/core/Mage/Core/Model/App.php(1339): Aoe_Scheduler_Model_Observer->dispatchAlways(Object(Varien_Event_Observer))
#5 app/code/core/Mage/Core/Model/App.php(1318): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatchAlways', Object(Varien_Event_Observer))
#6 app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('always', Array)
#7 cron.php(78): Mage::dispatchEvent('always')
#8 {main}

We are using updated AOE_Scheduler extension.

Version : 1.3.0

Please do the needful

**Comment by snowcore** [comment]
@sathishramesh1989 Check if your magento version is supported https://github.com/AOEpeople/Aoe_Scheduler#compability

**Comment by WRedMedia** [comment]
Same issue (Magento EE ver. 1.14.2.3).

**Comment by grafikchaos** [comment]
Which user owns the `var/locks/reindex_full.lock` ? I typically only see that error if the root user owns the lock file which may be caused by the cron job was setup by the root user instead of apache or nginx (i.e., `crontab -e -u nginx` ) or someone manually ran the `php shell/indexer.php` script or N98 Magerun as the root user.

**Comment by WRedMedia** [comment]
> or someone manually ran the php shell/indexer.php script or N98 Magerun as the root user.
Cron run reindexall avery 3 hours... How can i lock/pause crawler sheduler at this time ?

**Comment by hgpit** [comment]
Same problem.

EE v1.14.2.4

File constantly existing and modified every minute.
-rw-rw-rw-  1 magento apache   31 Jul 31 11:24 reindex_full.lock

My var/locks is 777.

If I delete the reindex_full.lock file, it re-appears within a minute (our cron is every minute).
AOE Scheduler has 'magento' as the user.

If I run reindexall from the command line, it runs fine (doesn't complain about any lock files existing).

**Comment by GowthamLeanSwift** [comment]
Any updates on this? We are facing the same issue.

**Comment by mzeis** [comment]
I'm facing the same issue.
