### ISSUE TITLE
Mage_Core_Model_App->getStore(NULL) in stock importer

### ISSUE THREAD

**Issue by seansan** [AOEpeople/Aoe_Scheduler#297]
Hi, we use a stock import module (xtento). they have debugged below and claim this is an error due to AOE. Personally not sure about this. But maybe it helps.  

Mage_Core_Model_Store_Exception in app/code/core/Mage/Core/Model/App.php:1377
Stack trace:
#0 app/code/core/Mage/Core/Model/App.php(848): Mage_Core_Model_App->throwStoreException()
#1 app/Mage.php(353): Mage_Core_Model_App->getStore(NULL)
#2 .modman/Aoe_Scheduler/app/code/community/Aoe/Scheduler/Helper/Data.php(281): Mage::getStoreConfig('system/cron/err...')
#3 .modman/Aoe_Scheduler/app/code/community/Aoe/Scheduler/Model/Schedule.php(260): Aoe_Scheduler_Helper_Data->sendErrorMail(Object(Aoe_Scheduler_Model_Schedule), 'Mage_Core_Model...')
#4 .modman/Aoe_Scheduler/app/code/community/Aoe/Scheduler/Model/Schedule.php(605): Aoe_Scheduler_Model_Schedule->runNow(true)
#5 .modman/Aoe_Scheduler/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#6 app/code/local/Xtento/StockImport/Model/Observer/Cron/Config.php(24): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#7 app/code/core/Mage/Core/Model/App.php(1358): Xtento_StockImport_Model_Observer_Cron_Config->addCronjobsToConfig(Object(Varien_Event_Observer))
#8 app/code/core/Mage/Core/Model/App.php(1331): Mage_Core_Model_App->_callObserverMethod(Object(Xtento_StockImport_Model_Observer_Cron_Config), 'addCronjobsToCo...', Object(Varien_Event_Observer))
#9 app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#10 .modman/Aoe_Scheduler/shell/scheduler.php(518): Mage::dispatchEvent('default', Array)
#11 .modman/Aoe_Scheduler/shell/scheduler.php(37): Aoe_Scheduler_Shell_Scheduler->cronAction()
#12 .modman/Aoe_Scheduler/shell/scheduler.php(545): Aoe_Scheduler_Shell_Scheduler->run()
#13 {main}

**Comment by seansan** [comment]
Anyone an idea? I dont know how to solve this one

**Comment by abpostman1** [comment]
Hi , same issue here ... found nothing about this but people saying it's because of multiple stores. But it's such a long time ago that i can't remember where i saw this answer.
Have you fixed this issue ?
Thanks

**Comment by joesken** [comment]
We're seeing the same issue - no fix found yet but if anyone else found one would be interested, thanks.

**Comment by Toinehaaijer** [comment]
`Mage_Core_Model_App->getStore(NULL)` cannot retrieve the store if the code is NULL.

A quick fix:

In app/code/core/Mage/Core/Model/App.php:
This line: `$id = $this->_currentStore;`
should be: `$id = $this->_currentStore ? $this->_currentStore : "default";`

(obviously extending the core files would be better for upgradability)

**Comment by seansan** [comment]
@Toinehaaijer
Did you remove your comment?
