### ISSUE TITLE
Zend Exception

### ISSUE THREAD

**Issue by newyorkwebdesign** [AOEpeople/Aoe_Scheduler#300]
Anyone has any ideas why this Zend Exception is occurring? 

exception 'Zend_Exception' with message 'dbModel read resource does not implement Zend_Db_Adapter_Abstract' in /####/#####/htdocs/lib/Varien/Data/Collection/Db.php:187
Stack trace:
#0 /####/#####//htdocs/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(134): Varien_Data_Collection_Db->setConnection(false)
#1 /####/#####/htdocs/app/code/core/Mage/Core/Model/Config.php(1354): Mage_Core_Model_Resource_Db_Collection_Abstract->__construct(Object(Mage_Cron_Model_Resource_Schedule))
#2 /####/#####/htdocs/app/code/core/Mage/Core/Model/Config.php(1386): Mage_Core_Model_Config->getModelInstance('cron_resource/s...', Object(Mage_Cron_Model_Resource_Schedule))
#3 /####/#####/htdocs/app/Mage.php(491): Mage_Core_Model_Config->getResourceModelInstance('cron/schedule_c...', Object(Mage_Cron_Model_Resource_Schedule))
#4 /####/#####/htdocs/app/code/core/Mage/Core/Model/Abstract.php(208): Mage::getResourceModel('cron/schedule_c...', Object(Mage_Cron_Model_Resource_Schedule))
#5 /####/#####/htdocs/app/code/core/Mage/Core/Model/Abstract.php(213): Mage_Core_Model_Abstract->getResourceCollection()
#6 /####/#####/htdocs/app/code/community/Aoe/Scheduler/Model/ProcessManager.php(95): Mage_Core_Model_Abstract->getCollection()
#7 /####/#####/htdocs/app/code/community/Aoe/Scheduler/Model/ProcessManager.php(144): Aoe_Scheduler_Model_ProcessManager->checkRunningJobs()
#8 /####/#####/htdocs/app/code/community/Aoe/Scheduler/Model/Observer.php(61): Aoe_Scheduler_Model_ProcessManager->watchdog()
#9 /####/#####/htdocs/app/code/core/Mage/Core/Model/App.php(1358): Aoe_Scheduler_Model_Observer->dispatchAlways(Object(Varien_Event_Observer))
#10 /####/#####/htdocs/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatchAlways', Object(Varien_Event_Observer))
#11 /####/#####/htdocs/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('always', Array)
#12 /####/#####/htdocs/shell/scheduler.php(377): Mage::dispatchEvent('always', Array)
#13 /####/#####/htdocs/shell/scheduler.php(37): Aoe_Scheduler_Shell_Scheduler->cronAction()
#14 /####/#####/htdocs/shell/scheduler.php(403): Aoe_Scheduler_Shell_Scheduler->run()
#15 {main}

Thanks for any help.

**Comment by jhuebel** [comment]
I'm receiving the same error. I installed from github using modman, I'm using PHP 7.0.8 with the Inchoo_PHP7 extension and I'm running Magento 1.9.3.1.
