### ISSUE TITLE
Strange Cron Error

### ISSUE THREAD

**Issue by behrang1981** [AOEpeople/Aoe_Scheduler#327]
Hi
i get this in the last couple of weeks.
Has anybody have a clue?

a:3:{i:0;s:0:"";i:1;s:1496:"#0 /home/cloudpanel/htdocs/mypage.tld/app/code/core/Mage/Core/Model/App.php(829): Mage_Core_Model_App->throwStoreException()
#1 /home/cloudpanel/htdocs/mypage.tld/app/Mage.php(353): Mage_Core_Model_App->getStore(NULL)
#2 /home/cloudpanel/htdocs/mypage.tld/app/code/community/Aoe/Scheduler/Helper/Data.php(266): Mage::getStoreConfig('system/cron/err...')
#3 /home/cloudpanel/htdocs/mypage.tld/app/code/community/Aoe/Scheduler/Model/Schedule.php(238): Aoe_Scheduler_Helper_Data->sendErrorMail(Object(Aoe_Scheduler_Model_Schedule), 'Mage_Core_Model...')
#4 /home/cloudpanel/htdocs/mypage.tld/app/code/community/Aoe/Scheduler/Model/Schedule.php(582): Aoe_Scheduler_Model_Schedule->runNow(true)
#5 /home/cloudpanel/htdocs/mypage.tld/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#6 /home/cloudpanel/htdocs/mypage.tld/app/code/core/Mage/Core/Model/App.php(1338): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#7 /home/cloudpanel/htdocs/mypage.tld/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#8 /home/cloudpanel/htdocs/mypage.tld/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#9 /home/cloudpanel/htdocs/mypage.tld/cron.php(76): Mage::dispatchEvent('default')
#10 {main}";s:11:"script_name";s:55:"/home/cloudpanel/htdocs/mypage.tld/index.php";}

greets

**Comment by joesken** [comment]
Probably duplicate of https://github.com/AOEpeople/Aoe_Scheduler/issues/297
