### ISSUE TITLE
Invalid model/method definition, expecting "model/class::method", got "" instead.'

### ISSUE THREAD

**Issue by Shemoz** [AOEpeople/Aoe_Scheduler#363]
I have a  Problem with Aoe Scheduler and a other Module (DHL Versenden). All other extensions works well, just this one makes a error with this message. Im using Magento Version 1.8.1.0 and Aoe Scheduler 1.5.1. Maybe someone has a tip for me.

> ---EXCEPTION---
> exception 'Mage_Core_Exception' with message 'Invalid model/method definition, expecting "model/class::method", got "" instead.' in /html/magento-de/app/Mage.php:595
> Stack trace:
> #0 /html/magento-de/app/code/community/Aoe/Scheduler/Helper/Data.php(313): Mage::throwException('Invalid model/m...')
> #1 /html/magento-de/app/code/community/Aoe/Scheduler/Model/Job.php(145): Aoe_Scheduler_Helper_Data->getCallBack('')
> #2 /html/magento-de/app/code/community/Aoe/Scheduler/Model/Schedule.php(213): Aoe_Scheduler_Model_Job->getCallback()
> #3 /html/magento-de/app/code/community/Aoe/Scheduler/Model/Schedule.php(623): Aoe_Scheduler_Model_Schedule->runNow(true)
> #4 /html/magento-de/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
> #5 /html/magento-de/app/code/core/Mage/Core/Model/App.php(1338): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
> #6 /html/magento-de/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
> #7 /html/magento-de/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
> #8 /html/magento-de/cron.php(75): Mage::dispatchEvent('default')
> #9 {main}

**Comment by jaycroll** [comment]
Bump. also having the same issue. using Magento 1.14.0.1

**Comment by jessicacarolinecosta** [comment]
Same issue with Magento 1.9.3.2

**Comment by m-overlund** [comment]
It is a known issue. 
Seems to be a conflict between Aoe Scheduler and modules that are using specific functions in their cron jobs.

Happens with MailChimp and Xtento's modules aswell:
- Mailchimp: https://github.com/mailchimp/mc-magento/issues/501#issuecomment-335159272
- Xtento: https://support.xtento.com/wiki/AOE_Scheduler:_Invalid_model_/_method_definition
