### ISSUE TITLE
Cron "deleteCustomerFlowPassword" not work with table prefix

### ISSUE THREAD

**Issue by Zap-Dev** [AOEpeople/Aoe_Scheduler#368]
All the other cron work

this cron (customer/observer::deleteCustomerFlowPassword) not work

I use table prefix **"storecustomer_flowpassword"** but i get this error from email
`
Base table or view not found: 1146 Table 'u47636738_up.customer_flowpassword' doesn't exist, query was: DELETE FROM `customer_flowpassword` WHERE (requested_date < '2018-02-28 00:00:01') i`

The table is storecustomer_flowpassword with prefix "store"

Where can I correct this bug?

```

PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'u47636738_up.customer_flowpassword' doesn't exist in /var/www/vhosts/mysite.it/httpdocs/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/vhosts/mysite.it/httpdocs/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/vhosts/mysite.it/httpdocs/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/vhosts/mysite.it/httpdocs/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 /var/www/vhosts/mysite.it/httpdocs/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /var/www/vhosts/mysite.it/httpdocs/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('DELETE FROM `cu...', Array)
#5 /var/www/vhosts/mysite.it/httpdocs/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('DELETE FROM `cu...', Array)
#6 /var/www/vhosts/mysite.it/httpdocs/lib/Zend/Db/Adapter/Abstract.php(664): Varien_Db_Adapter_Pdo_Mysql->query('DELETE FROM `cu...')
#7 /var/www/vhosts/mysite.it/httpdocs/app/code/core/Mage/Customer/Model/Observer.php(231): Zend_Db_Adapter_Abstract->delete('customer_flowpa...', '(requested_date...')
#8 /var/www/vhosts/mysite.it/httpdocs/app/code/community/Aoe/Scheduler/Model/Schedule.php(217): Mage_Customer_Model_Observer->deleteCustomerFlowPassword(Object(Aoe_Scheduler_Model_Schedule))
#9 /var/www/vhosts/mysite.it/httpdocs/app/code/community/Aoe/Scheduler/Model/Schedule.php(623): Aoe_Scheduler_Model_Schedule->runNow(true)
#10 /var/www/vhosts/mysite.it/httpdocs/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#11 /var/www/vhosts/mysite.it/httpdocs/app/code/core/Mage/Core/Model/App.php(1358): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#12 /var/www/vhosts/mysite.it/httpdocs/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#13 /var/www/vhosts/mysite.it/httpdocs/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#14 /var/www/vhosts/mysite.it/httpdocs/shell/scheduler.php(518): Mage::dispatchEvent('default', Array)
#15 /var/www/vhosts/mysite.it/httpdocs/shell/scheduler.php(37): Aoe_Scheduler_Shell_Scheduler->cronAction()
#16 /var/www/vhosts/mysite.it/httpdocs/shell/scheduler.php(545): Aoe_Scheduler_Shell_Scheduler->run()
#17 {main}

Next Zend_Db_Statement_Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'u47636738_up.customer_flowpassword' doesn't exist, query was: DELETE FROM `customer_flowpassword` WHERE (requested_date < '2018-02-28 00:00:01') in /var/www/vhosts/mysite.it/httpdocs/lib/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /var/www/vhosts/mysite.it/httpdocs/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/vhosts/mysite.it/httpdocs/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /var/www/vhosts/mysite.it/httpdocs/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/vhosts/mysite.it/httpdocs/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('DELETE FROM `cu...', Array)
#4 /var/www/vhosts/mysite.it/httpdocs/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('DELETE FROM `cu...', Array)
#5 /var/www/vhosts/mysite.it/httpdocs/lib/Zend/Db/Adapter/Abstract.php(664): Varien_Db_Adapter_Pdo_Mysql->query('DELETE FROM `cu...')
#6 /var/www/vhosts/mysite.it/httpdocs/app/code/core/Mage/Customer/Model/Observer.php(231): Zend_Db_Adapter_Abstract->delete('customer_flowpa...', '(requested_date...')
#7 /var/www/vhosts/mysite.it/httpdocs/app/code/community/Aoe/Scheduler/Model/Schedule.php(217): Mage_Customer_Model_Observer->deleteCustomerFlowPassword(Object(Aoe_Scheduler_Model_Schedule))
#8 /var/www/vhosts/mysite.it/httpdocs/app/code/community/Aoe/Scheduler/Model/Schedule.php(623): Aoe_Scheduler_Model_Schedule->runNow(true)
#9 /var/www/vhosts/mysite.it/httpdocs/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#10 /var/www/vhosts/mysite.it/httpdocs/app/code/core/Mage/Core/Model/App.php(1358): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#11 /var/www/vhosts/mysite.it/httpdocs/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#12 /var/www/vhosts/mysite.it/httpdocs/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#13 /var/www/vhosts/mysite.it/httpdocs/shell/scheduler.php(518): Mage::dispatchEvent('default', Array)
#14 /var/www/vhosts/mysite.it/httpdocs/shell/scheduler.php(37): Aoe_Scheduler_Shell_Scheduler->cronAction()
#15 /var/www/vhosts/mysite.it/httpdocs/shell/scheduler.php(545): Aoe_Scheduler_Shell_Scheduler->run()
#16 {main}
```

**Comment by sreichel** [comment]
This is not a problem of Aoe_Scheduler, it's bug in magento core:

- https://github.com/OpenMage/magento-lts/issues/162
- https://magento.stackexchange.com/questions/167559/magento-customer-reset-password-customer-flowpassword-error
