### ISSUE TITLE
Brightpearl - Mage_Core_Exception: Invalid model/method definition, expecting "model/class::method", got "" instead.

### ISSUE THREAD

**Issue by mustafaredsignal** [AOEpeople/Aoe_Scheduler#380]
I have a Problem with Aoe Scheduler and a other Module (Flint Brightpearl - https://www.flinttechnology.co.uk/store/brightpearl-connector.html). All other extensions works well, just this one makes a error with this message. Im using Magento Version 1.9.2.4 and Aoe Scheduler 1.5.0 Maybe someone has a tip for me.

---EXCEPTION---
Mage_Core_Exception: Invalid model/method definition, expecting "model/class::method", got "" instead. in /home/cloudpanel/htdocs/insulationpack/app/Mage.php:595
Stack trace:
#0 /home/cloudpanel/htdocs/insulationpack/app/code/community/Aoe/Scheduler/Helper/Data.php(314): Mage::throwException('Invalid model/m...')
#2 /home/cloudpanel/htdocs/insulationpack/app/code/community/Aoe/Scheduler/Model/Schedule.php(209): Aoe_Scheduler_Model_Job->getCallback()
#1 /home/cloudpanel/htdocs/insulationpack/app/code/community/Aoe/Scheduler/Model/Job.php(143): Aoe_Scheduler_Helper_Data->getCallBack('')
#3 /home/cloudpanel/htdocs/insulationpack/app/code/community/Aoe/Scheduler/Model/Schedule.php(605): Aoe_Scheduler_Model_Schedule->runNow(true)
#4 /home/cloudpanel/htdocs/insulationpack/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#5 /home/cloudpanel/htdocs/insulationpack/app/code/core/Mage/Core/Model/App.php(1358): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#6 /home/cloudpanel/htdocs/insulationpack/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#7 /home/cloudpanel/htdocs/insulationpack/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#8 /home/cloudpanel/htdocs/insulationpack/shell/scheduler.php(518): Mage::dispatchEvent('default', Array)
#9 /home/cloudpanel/htdocs/insulationpack/shell/scheduler.php(37): Aoe_Scheduler_Shell_Scheduler->cronAction()
#10 /home/cloudpanel/htdocs/insulationpack/shell/scheduler.php(545): Aoe_Scheduler_Shell_Scheduler->run()
#11 {main}

**Comment by mustafaredsignal** [comment]
No one here to take care of this issue?

**Comment by m-overlund** [comment]
Nope - it's pretty much deprecated, unfortunately.

I've had similar issues. If you're on a shared host with multiple php versions, please make sure that cron is handled with the same php version.

**Comment by mustafaredsignal** [comment]
Dear @m-overlund this is dedicated server on AWS with PHP 7.0.7-1. Only Brightpearl is conflicting and I am getting this issue.
