### ISSUE TITLE
Could not find a binary for md5sum

### ISSUE THREAD

**Issue by amcguireweb** [AOEpeople/Aoe_Scheduler#387]
Hello - I'm trying to configure crons to run locally on my Mac using brew. I am emailing myself via the crontab and continue to get the error "Could not find a binary for md5sum." Not sure how to resolve. I have installed md5sum.

<img width="572" alt="cron-error-md5sum" src="https://user-images.githubusercontent.com/8235324/50095751-2cf5fa80-01e4-11e9-9693-290a805a8e73.png">
 
Using Valet Plus for my local environment, Mac is on Mojave 10.14.2. Thanks for your time.

**Comment by amcguireweb** [comment]
Got it. Looks like for Mojave, **Full Disk Access** prevents you from changing system files (which includes privacy related data as well as system configuration like the crontabs).

https://stackoverflow.com/a/52590601/1830601

**Comment by amcguireweb** [comment]
After enabling Full Disk Access, the md5sum error stopped, but I began getting the following error:

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /lib/Zend/Db/Adapter/Pdo/Abstract.php:128
Stack trace:
#0 /lib/Zend/Db/Adapter/Pdo/Abstract.php(128): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /lib/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect()
#2 /lib/Varien/Db/Adapter/Pdo/Mysql.php(396): Zend_Db_Adapter_Pdo_Mysql->_connect()
#3 /lib/Zend/Db/Adapter/Abstract.php(460): Varien_Db_Adapter_Pdo_Mysql->_connect()
#4 /lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SET NAMES utf8', Array)
#5 /lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SET NAMES utf8', Array)
#6 /app/code/core/Mage/Core/Model/Resource.php(179): Varien_Db_Adapter_Pdo_Mysql-> in /lib/Zend/Db/Adapter/Pdo/Abstract.php on line 144
```

Changing **localhost** to **127.0.0.1** resolved this error and cron seems to now be working.

**Comment by amcguireweb** [comment]
I ended up copying the contents of _scheduler_cron.sh_ to _local_scheduler_cron.sh_, making the above changes, added the new local file to my .gitignore, and modified my local crontab to call the local bash script instead. Now it's working locally and on our development and production instances.
