### ISSUE TITLE
AoeSchedule on OpenMage on php7.4

### ISSUE THREAD

**Issue by Danieleeffe1** [AOEpeople/Aoe_Scheduler#395]
Goodmorning everyone

I installed the Aoe Schedule module to have more control of all magento cron.

I installed OpenMage on a server with php 7.4

When I try to generate a shedule the serever gives me this error:

[Wed Feb 24 08:03:59.484526 2021] [php7:error] [pid 205364] [client 108.162.229.14:32440] PHP Fatal error: Uncaught Error: Call to a member function generateSchedules() on bool in /var/www/html/magento2/openmage/app/code/community/Aoe/Scheduler/Controller/AbstractController.php:151\nStack trace:\n#0 /var/www/html/magento2/openmage/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Aoe_Scheduler_Controller_AbstractController->generateScheduleAction()\n#1 /var/www/html/magento2/openmage/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch()\n#2 /var/www/html/magento2/openmage/app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match()\n#3 /var/www/html/magento2/openmage/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()\n#4 /var/www/html/magento2/openmage/app/Mage.php(729): Mage_Core_Model_App->run()\n#5 /var/www/html/magento2/openmage/index.php(78): Mage::run()\n#6 {main}\n thrown in /var/www/html/magento2/openmage/app/code/community/Aoe/Scheduler/Controller/AbstractController.php on line 151

I can imagine it depends on the php version, but i don't know php javascript languages etc etc.

Suggestions on how to fix the problem?

**Comment by tmotyl** [comment]
@Danieleeffe1 are you using the newest aoe-scheduler from the master branch?

**Comment by Danieleeffe1** [comment]
Thanks for the reply

Maybe it was an outdated version

now i try the latest relase
